devathon/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('mess/', include('mess.urls')),
    path('admin/', admin.site.urls),
]

devathon2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('mess/', include('mess.urls')),
    path('admin/', admin.site.urls),
]

mess/urls.py
from django.urls import path
from . import views

app_name = 'mess'

urlpatterns = [
    path('', views.index, name='index'),
    path('wardenpageauthenticate/', views.wardenpageauthenticate, name='wardenpageauthenticate'),
    path('studentpageauthenticate/', views.studentpageauthenticate, name='studentpageauthenticate'),
    path('studentpage/<str:id>/', views.studentpage, name='studentpage'),
    path('wardenpage/<str:warden_id>/', views.wardenpage, name='wardenpage'),
    path('studentpage/<str:id>/logout/', views.logout_view, name='logout'),
    path('wardenpage/<str:warden_id>/logout/', views.logout_view1, name='logout1'),
    path('mess/<str:mess>/', views.mess, name='mess'),
    path('mess/<str:mess>/update', views.update, name='update')
]

mess/models.py
from django.db import models
from django.shortcuts import get_object_or_404
from datetime import date


class Warden(models.Model):
    name = models.CharField(max_length=4096)
    warden_id = models.CharField(max_length=20) 
    def __str__(self):
        return self.name

class Mess(models.Model):
    mess_name = models.CharField(max_length=4096, default="Ganga")
    breakfast_rate = models.IntegerField(default=0)
    lunch_rate = models.IntegerField(default=0)
    dinner_rate = models.IntegerField(default=0)
    extras_rate_breakfast = models.IntegerField(default=0)
    extras_rate_lunch = models.IntegerField(default=0)
    extras_rate_dinner = models.IntegerField(default=0)
    date = models.DateField(default=date.today)
    warden_id = models.ForeignKey(Warden, on_delete=models.CASCADE, default="123456")
    def __str__(self):
        return self.mess_name

class Student(models.Model):
    name = models.CharField(max_length=4096)
    student_id = models.CharField(max_length=20)
    year = models.IntegerField(default=1)
    mess = models.ForeignKey(Mess, on_delete=models.CASCADE)
    total_bill = models.IntegerField(default=0)

    def __str__(self):
        return self.student_id

class DailyBill(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    breakfast = models.BooleanField(default=False)
    lunch = models.BooleanField(default=False)
    dinner = models.BooleanField(default=False)
    extras_breakfast = models.IntegerField(default=0)
    extras_lunch = models.IntegerField(default=0)
    extras_dinner = models.IntegerField(default=0)
    date = models.DateField(default=date.today)
    update = models.BooleanField(default=False)


    def checkDate(self, mess_name):
        if self.date == get_object_or_404(Mess, date=self.date, name=mess_name):
            return True
        else:
            return False

    def __str__(self):
        return str(self.student)

mess/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, logout
from django.urls import reverse
from django.contrib.auth.models import User
from .models import Student, Warden, DailyBill, Mess
from django.utils import timezone
from datetime import date

def index(request):
    return render(request, 'mess/index.html', {'error_msg': False})

def wardenpageauthenticate(request):
    warden_id = request.POST['warden_username']
    warden_password = request.POST['warden_password']
    warden_present = authenticate(username = warden_id, password = warden_password)
    if warden_present is None:
        a = get_object_or_404(Warden, warden_id= warden_id)
        if a is not None:
            user = User.objects.create_user(warden_id, 'default@email.com', warden_password)
            user.save()
            warden_present = authenticate(username = warden_id, password = warden_password)

    if warden_present is not None and get_object_or_404(Warden, warden_id=warden_id):
        return HttpResponseRedirect(reverse('mess:wardenpage', args=(warden_id,)))
    else: 
        return render(request, 'mess/index.html', {'error_msg': True}) 
        
def studentpageauthenticate(request):
    student_id = request.POST['student_username']
    student_password = request.POST['student_password']
    student_present = authenticate(username = student_id, password = student_password)
    if student_present is None:
        a = get_object_or_404(Student, student_id = student_id)
        if a is not None:
            user = User.objects.create_user(student_id, 'default@email.com', student_password)
            user.save()
            student_present = authenticate(username = student_id, password = student_password)

    if student_present is not None and get_object_or_404(Student, student_id=student_id):
        return HttpResponseRedirect(reverse('mess:studentpage', args=(student_id,)))
    else: 
        return render(request, 'mess/index.html', {'error_msg': True})

def studentpage(request, id):
    if True:
        student = get_object_or_404(Student,student_id=id)
        t = timezone.now()
        date_today = t.strftime("%Y-%m-%d")
        try:
            dailybill = student.dailybill_set.get(date= date_today)
        except DailyBill.DoesNotExist:
            context = {
                'flag' : False,
                'total_bill': student.total_bill,
                'student_id': id,
            }
            return render(request, 'mess/studentpage.html', context) 

        bill = 0
        m = get_object_or_404(Mess, date= date_today,  mess_name = student.mess)
        if dailybill.breakfast is True: bill += m.breakfast_rate
        if dailybill.lunch is True: bill += m.lunch_rate
        if dailybill.dinner is True: bill += m.dinner_rate
        bill += (dailybill.extras_breakfast)*(m.extras_rate_breakfast)
        bill += (dailybill.extras_lunch)*(m.extras_rate_lunch)
        bill += (dailybill.extras_dinner)*(m.extras_rate_dinner)
        total_bill = student.total_bill
        context = {
            'flag': True,
            'dailybillset': dailybill,
            'mess_name': student.mess,
            'dailybill': bill,
            'student_id': id, 
            'total_bill': total_bill,   
        }
        return render(request, 'mess/studentpage.html', context)
    else:
        return HttpResponseRedirect(reverse('mess:index'))

def wardenpage(request, warden_id): 
    warden = get_object_or_404(Warden, warden_id= warden_id)
    mess = Mess.objects.filter(warden_id= warden.pk)
    context = {
        'warden': warden,
        'mess_list': mess,
    }
    return render(request, 'mess/wardenpage.html', context)

def mess(request, mess):
    mess_record = get_object_or_404(Mess, mess_name = mess)
    warden = get_object_or_404(Warden, name = mess_record.warden_id)
    context = {
        'mess_record': mess_record,
        'warden': warden
    }
    return render(request, 'mess/mess.html', context)

def update(request, mess):
    messx = get_object_or_404(Mess, mess_name = mess)
    warden = get_object_or_404(Warden, name = messx.warden_id)
    messx.breakfast_rate  = request.POST['bname']
    messx.lunch_rate = request.POST['lname']
    messx.dinner_rate = request.POST['dname']
    messx.extras_rate_breakfast = request.POST['bxname']
    messx.extras_rate_lunch = request.POST['exname']
    messx.extra_rate_dinner = request.POST['dxname'] 
    messx.date = date.today
    messx.save()
    return HttpResponseRedirect(reverse('mess:wardenpage', args=(warden.warden_id,)))

def logout_view(request, id):
    logout(request)
    return HttpResponseRedirect(reverse('mess:index'))

def logout_view1(request, warden_id):
    logout(request)
    return HttpResponseRedirect(reverse('mess:index'))

devathon2/__pycache__/templates/mess/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- index page css file -->
    <link rel="stylesheet" type="text/css" href="{% static 'mess/index.css' %}">

    <title>nitw@mess</title>
  </head>
  <body>
 
<div class="container mt-3" id="header_part">
  <img src="{%static 'mess/logo.jpg'%}" class="image-fluid">
  <h2 class="ml-4">National Institue of Technology Warangal</h2>

</div>
<div class="container my-3 p-2" id="title_line">
  <h2>
    Student - Mess Records
  </h2>
  
</div>
 <h3 class="container my-3">Please login to proceed</h3>
 {% if error_msg %}<h4 class="container my-3">Invalid username or password</h4><br>{% endif %}
 <div class="container p-2" id="login_forms">
  <div class="container my-2 mr-1" id ="student_login">
    <div class="container my-2" id="student_login_header_part">
      <img src="{%static 'mess/student_icon.png'%}" class="image-fluid m-2">
      <h5 class="m-2">Student Login</h5>
    </div>
    <form class="container-fluid" action="{% url 'mess:studentpageauthenticate'%}" method="POST">
      {% csrf_token %}
      <input type="text" name="student_username" placeholder="Userame" class="container-fluid my-2 p-2" required>
      
     
       <input type="password" name="student_password" placeholder="Password" class="container-fluid my-2 p-2" required>
      <div class="container-fluid my-3">
         <div class="float-left">
          <input type="checkbox" name="remember_me"class=""><label class="mx-2">Remember Me</label>
          </div>
       <a href="#" class="float-right"><button class="forgot_button">Forgot Password ?</button></a>

      </div>
       <input type="submit" value="Login" class="container my-5 sbmt_btn">
   
    </form>
    
  </div>
  <!-- <div id="break_line" class="mx-2"></div> -->
  <div class="container my-2 ml-1" id="warden_login">
    <div class="container my-2" id="warden_login_header_part">
      <img src="{%static 'mess/warden_icon.png'%}" class="image-fluid m-2">
      <h5 class="m-2">Warden Login</h5>
    </div> 
     <form class="container-fluid" action="{% url 'mess:wardenpageauthenticate'%}" method="POST">
      {% csrf_token %}
      <input type="text" name="warden_username" placeholder="Userame" class="container-fluid my-2 p-2" required>
      
     
       <input type="password" name="warden_password" placeholder="Password" class="container-fluid my-2 p-2" required>
      <div class="container-fluid my-3">
         <div class="float-left">
          <input type="checkbox" name="remember_me"class=""><label class="mx-2">Remember Me</label>
          </div>
       <a href="#" class="float-right"><button class="forgot_button">Forgot Password ?</button></a>

      </div>
       <input type="submit" value="Login" class="container my-5 sbmt_btn">
   
    </form>
  </div>
</div>

<footer class="container foter my-4 p-2">
   <p>for any query feel free to contact us at support_wsdc@gmail.com</p>
  <p>all right reserved &copy WSDC , Nit Warangal</p>
 
</footer>



















    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

devathon2/__pycache__/templates/mess/studentpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- index page css file -->
    <link rel="stylesheet" type="text/css" href="{% static 'mess/index.css' %}">

    <title>student@mess</title>
  </head>
  <body>
 
<div class="container-fluid" id="header_part">
  <h2 class="ml-4">Mess II {{student_id}}</h2>
</div>
<div class="container my-3 p-2" id="title_line">
  <h3>
    Current Bill
  </h3>
   <h1 class="bill">{{total_bill}}</h1>
</div>
<div class="container my-3 p-2" id="title_line">
  <h3>
    Today's Extras
  </h3>
  <ul>
      <li class="item"> 
          extras          x{{daily_bill.extras}}
      </li>
      <li class="item">
          today's bill    {{todays_bill}}
      </li>
  </ul>
</div>
<div class="container my-3 p-2"><button class="APPROVE">APPROVE</button></div>
<footer class="container foter my-4 p-2">
   <p>for any query feel free to contact us at support_wsdc@gmail.com</p>
  <p>all right reserved &copy WSDC , Nit Warangal</p>
 
</footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

devathon2/__pycache__/templates/mess/wardenpage.html
<!doctype html>
<head>
    <title>
        Devathon
    </title>
</head>
<body>
    <a href="{%url 'mess:logout' warden_id%}">logout</a>
</body>

mess/templates/mess/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- index page css file -->
    <link rel="stylesheet" type="text/css" href="{% static 'mess/index.css' %}">

    <title>nitw@mess</title>
  </head>
  <body>
 
<div class="container mt-3" id="header_part">
  <img src="{%static 'mess/logo.jpg'%}" class="image-fluid">
  <h2 class="ml-4">National Institue of Technology Warangal</h2>

</div>
<div class="container my-3 p-2" id="title_line">
  <h2>
    Student - Mess Records
  </h2>
  
</div>
 <h3 class="container my-3">Please login to proceed</h3>
 {% if error_msg %}<h4 class="container my-3">Invalid username or password</h4><br>{% endif %}
 <div class="container p-2" id="login_forms">
  <div class="container my-2 mr-1" id ="student_login">
    <div class="container my-2" id="student_login_header_part">
      <img src="{%static 'mess/student_icon.png'%}" class="image-fluid m-2">
      <h5 class="m-2">Student Login</h5>
    </div>
    <form class="container-fluid" action="{% url 'mess:studentpageauthenticate' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="student_username" placeholder="Userame" class="container-fluid my-2 p-2" required>
      
     
       <input type="password" name="student_password" placeholder="Password" class="container-fluid my-2 p-2" required>
      <div class="container-fluid my-3">
         <div class="float-left">
          <input type="checkbox" name="remember_me"class=""><label class="mx-2">Remember Me</label>
          </div>
       <a href="#" class="float-right"><button class="forgot_button">Forgot Password ?</button></a>

      </div>
       <input type="submit" value="Login" class="container my-5 sbmt_btn">
   
    </form>
    
  </div>
  <!-- <div id="break_line" class="mx-2"></div> -->
  <div class="container my-2 ml-1" id="warden_login">
    <div class="container my-2" id="warden_login_header_part">
      <img src="{%static 'mess/warden_icon.png'%}" class="image-fluid m-2">
      <h5 class="m-2">Warden Login</h5>
    </div> 
     <form class="container-fluid" action="{% url 'mess:wardenpageauthenticate' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="warden_username" placeholder="Userame" class="container-fluid my-2 p-2" required>
      
     
       <input type="password" name="warden_password" placeholder="Password" class="container-fluid my-2 p-2" required>
      <div class="container-fluid my-3">
         <div class="float-left">
          <input type="checkbox" name="remember_me"class=""><label class="mx-2">Remember Me</label>
          </div>
       <a href="#" class="float-right"><button class="forgot_button">Forgot Password ?</button></a>

      </div>
       <input type="submit" value="Login" class="container my-5 sbmt_btn">
   
    </form>
  </div>
</div>

<footer class="container foter my-4 p-2">
   <p>for any query feel free to contact us at support_wsdc@gmail.com</p>
  <p>all right reserved &copy WSDC , Nit Warangal</p>
 
</footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

mess/templates/mess/mess.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- index page css file -->
    <link rel="stylesheet" type="text/css" href="{% static 'mess/index.css' %}">
    <!-- warden page css -->
    <link rel="stylesheet" type="text/css" href="{% static 'mess/warden.css' %}">
    <!-- mess1 css -->
    <link rel="stylesheet" type="text/css" href="{% static 'mess/mess1.css' %">
    <title>{{mess_record.mess_name}}</title>
  </head>
  <body>
 
<div class="container mt-3" id="header_part">
  <img src="{% static 'mess/logo.jpg' %}" class="image-fluid">
  <h2 class="ml-4">National Institue of Technology Warangal</h2>

</div>
<div class="container my-3 p-2" id="title_line">
  <h2>
    Student - Mess Records
  </h2>
  
</div>

 <div class="container " id="mess_detail">
   <h5>Name of Mess : <span>{{mess_record.mess_name}}</span></h5>
   <h5>Warden of Mess : <span>{{warden.name}}</span></h5>
 </div>
 <h4 class="container my-2 p-1" id="today">Today's Price and Extra's Plan</h4>

 <div class="container">
  <form action="{% url 'mess:update' mess_record.mess_name%}" method="POST">
    {% csrf_token %}
    <label for="bname">BreakFast:</label>
    <input type="text" id="bname" name="bname" value={{mess_record.breakfast_rate}}><br><br> 
    <label for="lame">Lunch:</label>
    <input type="text" id="lname" name="lname" value={{mess_record.lunch_rate}}><br><br>
    <label for="dname">dinner:</label>
    <input type="text" id="dname" name="dname", value={{mess_record.dinner_rate}}><br><br>  
    <label for="bxname">BreakFast Extra:</label>
    <input type="text" id="bxname" name="bxname" value={{mess_record.extras_rate_breakfast}}><br><br>
    <label for="exname">Lunch Extra:</label>
    <input type="text" id="exname" name="exname" value={{mess_record.extras_rate_lunch}}><br><br>
    <label for="dxname">Dinner Extra:</label>
    <input type="text" id="dxname" name="dxname" value={{mess_record.extras_rate_dinner}}><br><br>
    <input type="submit" value="Submit">
  </form>
</div>

 </div>
<footer class="container foter my-4 p-2">
   <p>for any query feel free to contact us at support_wsdc@gmail.com</p>
  <p>all right reserved &copy WSDC , Nit Warangal</p>
 
</footer>



















    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

mess/templates/mess/studentpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- index page css file -->
    <link rel="stylesheet" type="text/css" href="{% static 'mess/index.css' %}">

    <title>
      student@mess
    </title>

  </head>
  <body>
 
<div class="container-fluid" id="header_part">
  <h2 class="ml-4">{{mess_name}} Mess<br> {{student_id}}</h2>
  <h5 style="float: right;"><a href="{% url 'mess:logout' student_id %}"><br>logout </a></h5>
</div>
<div class="container my-3 p-2" id="title_line">
  <h3>
    Current Bill
  </h3>
   <h1 class="bill">{{total_bill}}</h1>
</div>
<div class="container my-3 p-2" id="title_line">
  {% if flag %}
  <h3>
    Today's Extras
  </h3>
  <ul>
    <li class="item">
      extras in breakfast -- {{dailybillset.extras_breakfast}}
    </li>
    <li class="item">
      extras in lunch --  {{dailybillset.extras_lunch}}
    </li>
    <li class="item">
      extras in dinner -- {{dailybillset.extras_dinner}}
    </li>
    <li class="item"> 
      extras Bill -- {{dailybill}}
    </li>
    {% else %}
      <li class="item">
        Bill has not been updated yet
      </li>
    {% endif %}
  </ul>
</div>
<div class="container my-3 p-2"><button class="COMPLAINTS">COMPLAINTS</button></div>
<footer class="container foter my-4 p-2">
   <p>for any query feel free to contact us at support_wsdc@gmail.com</p>
  <p>all right reserved &copy WSDC , Nit Warangal</p>
 
</footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>